### ISSUE TITLE
Update Bulma to 0.8.0

### ISSUE THREAD

**Issue by juliomotol** [jloh/bulma-prefers-dark#19]
Any plans on updating bulma to [0.8.0](https://github.com/jgthms/bulma/releases/tag/0.8.0)?

**Comment by jloh** [comment]
Hey! I have plans to support 0.8.0 for sure, hoping to find the time to update this soon!

**Comment by juliomotol** [comment]
Closing this issue in favor of the dependency PR https://github.com/jloh/bulma-prefers-dark/pull/5
