### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by HopefulLlama** [jloh/bulma-prefers-dark#38]
There's a few issues I'd like to highlight and possibly contribute to, but of course I'd like to know if this repo is being maintained.

**Comment by jloh** [comment]
Hi @HopefulLlama. I don't use Bulma anymore unfortunately so don't actively develop this repo anymore. I'm more than happy to merge PRs that come through and release a new version here or there however.

Hopefully that helps.
